/**
 * Backfill descriptive alt text onto existing ProductMedia rows.
 *
 * The original import derived alt text from upload filenames and stripped only
 * ".png", leaving rows like:
 *
 *   "Zewa Feeds Guppy Bites G2 — Guppy 03.jpg"
 *   "Zewa Feeds Guppy Bites G2 — 1"
 *
 * Re-running the importer would fix these, but it also re-uploads every asset.
 * This rewrites the alt column in place instead.
 *
 * The stored value is "<product name> — <filename stem>", so the fragment after
 * the em dash is recovered and fed back through buildMediaAlt. Where that is not
 * the shape (hand-written alt, or the video rows, which were always correct),
 * the row is left alone — a human-authored description must never be
 * overwritten by a generated one.
 *
 * Idempotent: re-running it changes nothing once the rows are clean.
 *
 *   npx tsx scripts/fix-media-alt.ts          # preview only
 *   npx tsx scripts/fix-media-alt.ts --write  # apply
 */
import { PrismaClient } from '@prisma/client';
import { buildMediaAlt } from '../src/lib/media-alt';

const prisma = new PrismaClient();
const WRITE = process.argv.includes('--write');

async function main() {
  const media = await prisma.productMedia.findMany({
    orderBy: [{ familyId: 'asc' }, { position: 'asc' }],
    include: { family: { select: { name: true } } },
  });

  let changed = 0;
  let skipped = 0;

  /*
   * Two different shots can reduce to the same description — a product with
   * both "M3 200G Back 1" and "M3 200G Back Blinkit" yields "back of pack …"
   * twice. Identical alt text on adjacent images is the very problem this
   * script exists to fix, so repeats within a product get a numeric suffix.
   */
  const seen = new Map<string, number>();

  for (const m of media) {
    const name = m.family?.name;
    if (!name || !m.alt) {
      skipped++;
      continue;
    }

    // Videos already read correctly ("… — product video"); leave them.
    if (m.type !== 'IMAGE') {
      skipped++;
      continue;
    }

    const prefix = `${name} — `;
    if (!m.alt.startsWith(prefix)) {
      // Not generated by the importer — assume a human wrote it.
      skipped++;
      continue;
    }

    const stem = m.alt.slice(prefix.length);
    const base = buildMediaAlt(name, stem, m.position ?? 0);

    const key = `${m.familyId}::${base}`;
    const nth = (seen.get(key) ?? 0) + 1;
    seen.set(key, nth);
    const next = nth === 1 ? base : `${base} (${nth})`;

    if (next === m.alt) {
      skipped++;
      continue;
    }

    console.log(`  ${m.alt}\n    -> ${next}`);
    if (WRITE) {
      await prisma.productMedia.update({ where: { id: m.id }, data: { alt: next } });
    }
    changed++;
  }

  console.log(
    `\n${WRITE ? 'Updated' : 'Would update'} ${changed} row(s); ${skipped} left unchanged.`,
  );
  if (!WRITE && changed > 0) console.log('Re-run with --write to apply.');
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
